version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_LOCK_DIR=/var/lock/apache2
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - APACHE_RUN_DIR=/var/run/apache2
